### PR TITLE
Allow accepting file containing test files to run - add support for env var KNAPSACK_TEST_FILE_LIST_SOURCE_FILE

### PR DESCRIPTION
**Pull request by alexanderjeurissen**
ref: https://github.com/KnapsackPro/knapsack_pro-ruby/pull/129

This *PR* adds support for this behavior to the regular `knapsack` gem.

### CODE REVIEW

**Comment by alexanderjeurissen** [comment]
@ArturT Any chance of this getting merged in upstream ?

**Comment by ArturT** [comment]
Hi @alexanderjeurissen 

This feature is specific to the `knapsack_pro` version. More about it here https://knapsackpro.com/faq/question/how-to-run-a-specific-list-of-test-files-or-only-some-tests-from-test-file

Support from users who use the `knapsack_pro` gem helps us keep maintaining the project and provide ongoing support for the users.

At the moment we have a pretty busy time with other priorities so we haven't decided yet whether to introduce the same feature into the `knapsack` gem. We might revisit this PR later.

If you like you can [try out the `knapsack_pro` gem version](http://knapsackpro.com/) in the meantime and we can help with the setup. If you have an open-source project then you can use it for free. Feel free to [contact us](https://knapsackpro.com/contact). We can always find a win-win solution for your team and provide technical tips on how to improve your CI setup.

Cheers

**Comment by wscourge** [comment]
@ArturT how is it going with the decision?

**Comment by ArturT** [comment]
@wscourge At this moment, we abstain from the decision to introduce new features.

I hope in 2023, we will clarify the high-level plans so that we can put more focus on delivering value to users. We will better understand how the knapsack gem fits into that.

**Comment by 3v0k4** [comment]
We officially archived Knapsack, you can read more about it in the [README](https://github.com/KnapsackPro/knapsack).

Thank you for caring and creating this PR.

I'm sorry we couldn't get this done for you.

**Pull request closed without merging**
